from __future__ import annotations


FEATURE_SCHEMA_VERSION = "feature-schema-v3"
BENIGN_REGIME_VALUE = "none"
GENERATION_PROCESS_COLUMNS = [
    "num_chunks",
    "chunk_strategy",
    "avg_chunk_len",
]

FEATURE_COLUMNS = [
    "page_width",
    "page_height",
    "num_text_objects",
    "num_text_outside_page_bounds",
    "frac_text_outside_page",
    "num_text_negative_coords",
    "max_abs_x",
    "max_abs_y",
    "max_distance_from_page_center",
    "mean_distance_from_page_center",
    "coord_entropy_x",
    "coord_entropy_y",
    "bbox_area_mean",
    "bbox_area_std",
    "quadrant_density_q1",
    "quadrant_density_q2",
    "quadrant_density_q3",
    "quadrant_density_q4",
    "min_font_size",
    "max_font_size",
    "mean_font_size",
    "std_font_size",
    "num_font_lt_1",
    "num_font_lt_2",
    "num_font_lt_3",
    "frac_small_font_objects",
    "font_size_skewness",
    "num_render_mode_3",
    "frac_render_mode_3",
    "num_nonstandard_render_modes",
    "num_white_text",
    "frac_white_text",
    "white_text_on_white_bg_flag",
    "num_pages",
    "num_content_streams_total",
    "mean_streams_per_page",
    "std_streams_per_page",
    "artifact_bmc_count",
    "artifact_emc_count",
    "has_artifact_wrapper",
    "num_text_show_ops",
    "num_stream_objects",
    "avg_stream_length_bytes",
    "max_stream_length_bytes",
    "extractor_char_count",
    "render_visible_char_estimate",
    "char_count_difference",
    "char_mismatch_ratio",
    "text_density_per_page",
    "injection_cluster_score",
    "coord_variance_x",
    "coord_variance_y",
    "distance_outlier_score",
]

FEATURE_GROUPS = {
    "spatial": [
        "page_width",
        "page_height",
        "num_text_objects",
        "num_text_outside_page_bounds",
        "frac_text_outside_page",
        "num_text_negative_coords",
        "max_abs_x",
        "max_abs_y",
        "max_distance_from_page_center",
        "mean_distance_from_page_center",
        "coord_entropy_x",
        "coord_entropy_y",
        "bbox_area_mean",
        "bbox_area_std",
        "quadrant_density_q1",
        "quadrant_density_q2",
        "quadrant_density_q3",
        "quadrant_density_q4",
        "coord_variance_x",
        "coord_variance_y",
        "distance_outlier_score",
    ],
    "font": [
        "min_font_size",
        "max_font_size",
        "mean_font_size",
        "std_font_size",
        "num_font_lt_1",
        "num_font_lt_2",
        "num_font_lt_3",
        "frac_small_font_objects",
        "font_size_skewness",
    ],
    "rendering": [
        "num_render_mode_3",
        "frac_render_mode_3",
        "num_nonstandard_render_modes",
        "num_white_text",
        "frac_white_text",
        "white_text_on_white_bg_flag",
    ],
    "structural": [
        "num_pages",
        "num_content_streams_total",
        "mean_streams_per_page",
        "std_streams_per_page",
        "artifact_bmc_count",
        "artifact_emc_count",
        "has_artifact_wrapper",
        "num_text_show_ops",
        "num_stream_objects",
        "avg_stream_length_bytes",
        "max_stream_length_bytes",
    ],
    "mismatch": [
        "extractor_char_count",
        "render_visible_char_estimate",
        "char_count_difference",
        "char_mismatch_ratio",
    ],
    "distribution": [
        "text_density_per_page",
        "injection_cluster_score",
    ],
}

REGIME_COLUMNS = [
    "source_type",
    "spatial_regime",
    "rendering_regime",
    "structural_regime",
    "message_type",
    "attack_family",
    "benign_confounder_family",
]

ANALYSIS_ONLY_COLUMNS = [
    "spatial_regime",
    "rendering_regime",
    "structural_regime",
    "message_type",
    "attack_family",
    "attack_strength",
    "benign_confounder_family",
    "artifact_wrapper",
    "base_pdf_id",
    "pair_id",
    "triad_id",
    "pdf_role",
    "source_type",
    "message_variant_id",
    "target_message_type",
    "target_attack_family",
    "target_benign_confounder_family",
    "target_physical_attack_family",
    "target_physical_attack_strength",
    "target_physical_structural_regime",
    "target_physical_spatial_regime",
    "target_physical_rendering_regime",
    "target_physical_artifact_wrapper",
    "confounder_physical_attack_family",
    "confounder_physical_attack_strength",
    "confounder_physical_structural_regime",
    "confounder_physical_spatial_regime",
    "confounder_physical_rendering_regime",
    "confounder_physical_artifact_wrapper",
    "policy_message_source",
    "raw_injected_text",
    "message_length_chars",
    *GENERATION_PROCESS_COLUMNS,
]

FORBIDDEN_FEATURE_COLUMNS = {
    "pdf_id",
    "base_pdf_id",
    "file_path",
    "label",
    "source_type",
    "spatial_regime",
    "rendering_regime",
    "structural_regime",
    "message_type",
    "attack_family",
    "attack_strength",
    "benign_confounder_family",
    "artifact_wrapper",
    "split_group",
    "pair_id",
    "triad_id",
    "pdf_role",
    "message_variant_id",
    "target_message_type",
    "target_attack_family",
    "target_benign_confounder_family",
    "target_physical_attack_family",
    "target_physical_attack_strength",
    "target_physical_structural_regime",
    "target_physical_spatial_regime",
    "target_physical_rendering_regime",
    "target_physical_artifact_wrapper",
    "confounder_physical_attack_family",
    "confounder_physical_attack_strength",
    "confounder_physical_structural_regime",
    "confounder_physical_spatial_regime",
    "confounder_physical_rendering_regime",
    "confounder_physical_artifact_wrapper",
    "policy_message_source",
    "raw_injected_text",
    "message_length_chars",
    *GENERATION_PROCESS_COLUMNS,
    "dataset_split",
    "source_original_filename",
    "resolved_file_path",
    "parse_errors",
    "feature_schema_version",
    "file_size",
    "byte_size",
    "stream_length_bytes",
}

REQUIRED_METADATA_COLUMNS = [
    "pdf_id",
    "base_pdf_id",
    "file_path",
    "label",
    "source_type",
    "spatial_regime",
    "rendering_regime",
    "structural_regime",
    "message_type",
    "attack_family",
    "benign_confounder_family",
    "message_variant_id",
    "artifact_wrapper",
    "split_group",
]
