import argparse
import json
import os
import sys
from typing import Any, Dict, Optional, Tuple


def _find_metadata_json(start_path: str, max_levels: int = 8) -> Optional[str]:
    """
    Given a path to a PDF stored in our storage layout, walk upward to find
    the nearest metadata.json that the pipeline writes.
    """
    current = os.path.abspath(os.path.dirname(start_path))
    for _ in range(max_levels + 1):
        candidate = os.path.join(current, "metadata.json")
        if os.path.isfile(candidate):
            return candidate
        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent
    return None


def _get_nested(obj: Any, path: Tuple[str, ...]) -> Any:
    cur = obj
    for key in path:
        if not isinstance(cur, dict) or key not in cur:
            return None
        cur = cur[key]
    return cur


def _extract_injection_settings(metadata_obj: Dict[str, Any]) -> Tuple[Optional[Dict[str, Any]], Optional[str]]:
    """
    Return (injectionSettings, sourcePathLabel).
    """
    candidates = [
        ("root.injectionSettings", ("injectionSettings",)),
        ("root.metadata.injectionSettings", ("metadata", "injectionSettings")),
        ("root.pipeline.watermarking.metadata.injectionConfig", ("pipeline", "watermarking", "metadata")),
    ]
    for label, p in candidates:
        value = _get_nested(metadata_obj, p)
        if isinstance(value, dict) and value:
            return value, label
    return None, None


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Inspect injection settings for a PDF generated by this pipeline. "
            "This reads the sidecar metadata.json written by the backend."
        )
    )
    parser.add_argument("pdf_path", help="Path to a PDF under ./storage/... (uploads/ or processed/).")
    parser.add_argument(
        "--metadata-json",
        dest="metadata_json",
        default=None,
        help=(
            "Optional explicit path to metadata.json. "
            "If provided, the script will use it instead of searching upward from the PDF path."
        ),
    )
    args = parser.parse_args()

    pdf_path = args.pdf_path
    if not os.path.isfile(pdf_path):
        print(f"ERROR: PDF not found: {pdf_path}", file=sys.stderr)
        return 2

    metadata_path = args.metadata_json or _find_metadata_json(pdf_path)
    if not metadata_path:
        print(
            "ERROR: Could not find metadata.json by walking upward from the PDF path.\n"
            "This inspector expects PDFs stored under the project storage layout (./storage/...)\n"
            "where metadata.json lives at the document root.\n"
            "If you downloaded/moved the PDF elsewhere, pass --metadata-json with the original metadata.json path.",
            file=sys.stderr,
        )
        return 3
    if not os.path.isfile(metadata_path):
        print(f"ERROR: metadata.json not found: {metadata_path}", file=sys.stderr)
        return 3

    try:
        with open(metadata_path, "r", encoding="utf-8") as f:
            metadata_obj = json.load(f)
    except Exception as e:
        print(f"ERROR: Failed to read metadata.json: {metadata_path} ({e})", file=sys.stderr)
        return 4

    injection_settings, source_label = _extract_injection_settings(metadata_obj)
    if not injection_settings:
        print(
            "ERROR: metadata.json found but injectionSettings not present.\n"
            f"metadata.json: {metadata_path}",
            file=sys.stderr,
        )
        return 5

    # Prefer the canonical injectionSettings shape written by /api/documents.
    message_type = None
    injection_config = None
    if "messageType" in injection_settings:
        message_type = injection_settings.get("messageType")
        injection_config = injection_settings.get("injectionConfig")
    else:
        # Some contexts might pass through watermarking metadata directly.
        message_type = _get_nested(metadata_obj, ("metadata", "messageType")) or _get_nested(metadata_obj, ("messageType",))
        injection_config = injection_settings.get("injectionConfig") or injection_settings.get("injection_config")

    if not isinstance(injection_config, dict):
        injection_config = {}

    out = {
        "pdf_path": os.path.abspath(pdf_path),
        "metadata_json": os.path.abspath(metadata_path),
        "source": source_label,
        "message_type": message_type,
        "spatial_regime": injection_config.get("spatial_regime"),
        "rendering_regime": injection_config.get("rendering_regime"),
        "structural_regime": injection_config.get("structural_regime"),
        "artifact_wrapper": injection_config.get("artifact_wrapper"),
        "font_size": injection_config.get("font_size"),
        "coordinates": injection_config.get("coordinates"),
    }

    print(json.dumps(out, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
